### ISSUE TITLE
Getting error on liquidity actions

### ISSUE THREAD

**Issue by DevdevQ** [ston-fi/sdk#18]
Provide liquidity is success, but not work burn liquidity

I use testnet router (EQBsGx9ArADUrREB34W-ghgsCgBShvfUr4Jvlu-0KGc33Rbt)

![Provide code](https://github.com/ston-fi/sdk/assets/172047316/e43f0701-44fa-4b58-ae52-ca19c45b4d25)
![Burn code](https://github.com/ston-fi/sdk/assets/172047316/c12fc94a-c37e-4460-9acb-1c68e3589344)

get error on `const lpTokenWalletData = await lpTokenWallet.getData();`

![Error](https://github.com/ston-fi/sdk/assets/172047316/cc25065c-8209-4d4e-9796-fe3f3a65a62a)

Example of jetton master address [https://testnet.tonviewer.com/kQA0v8o1d6kjOUh9tIM6YNVEYbTKbCHCSa6yowmpCQPdkb9Z](https://testnet.tonviewer.com/kQA0v8o1d6kjOUh9tIM6YNVEYbTKbCHCSa6yowmpCQPdkb9Z)

Example of pool address [https://testnet.tonviewer.com/kQD0iLCED_H1Khw27mqitXz9FI4J-lfb8atogNIsGWYYBECF](https://testnet.tonviewer.com/kQD0iLCED_H1Khw27mqitXz9FI4J-lfb8atogNIsGWYYBECF)

**Comment by pavel-rakhmanov** [comment]
Ok, if I read the transaction history of [this pool](https://testnet.tonviewer.com/kQD0iLCED_H1Khw27mqitXz9FI4J-lfb8atogNIsGWYYBECF) correctly, you only created it with [this transaction](https://testnet.tonviewer.com/transaction/8f304deddf154eebfe69db924834afc0c5a0f9de79b521a8bd7f98310a7a9733). And newer provide liquidity to it later. 

The first liquidity provision to the pool [as described in our docs](https://docs.ston.fi/docs/developer-section/architecture#creating-a-pool) is unique. All the LP tokens during the first liquidity provision will be sent to a null address. This is a reason why lpTokenWallet address of this pool for a user wallet "0QBqbwUbvyB5TxPLQ-LCDduMHjYX5AjPDtPeE5Un5YMwQNON" does not exist yet. Because of that, the getData method on a non-existing contract throws an error

Just make one more successful liquidity provision to this pool, and then LP wallet contract will be deployed for your user wallet.
