### ISSUE TITLE
Issue with Jetton to TON Transaction Using TON Connect from Address A to Address B

### ISSUE THREAD

**Issue by sinanouri** [ston-fi/sdk#24]
When trying to generate a Jetton to TON transaction to send via TON Connect, my transaction fails. I am trying to send PEPE from `UQBtlqrwYrbsWKMZ9mjmP-5eGuYVyBOXLblc5SRqhAl-cwpM` and receive TON in `UQCf2G7AWNW0NsagLK1Y2rzWcgJCk5dJ7VwRWXOuvXRgSLaj`

```javascript
const swapObject = await router.getSwapJettonToTonTxParams({
    userWalletAddress: "UQCf2G7AWNW0NsagLK1Y2rzWcgJCk5dJ7VwRWXOuvXRgSLaj",
    offerJettonAddress: "EQCXzO7HhoK5fDQuCONE43l8-Qsreq5zq89ZVNhEna24eK-h",
    offerAmount: BigInt("100000000000"),
    proxyTon: new pTON.v1(),
    minAskAmount: "20727292",
    queryId: 1,
});

const to = swapObject.to.toString();
const value = swapObject.value.toString();
const payload = swapObject.body?.toBoc().toString("base64");
/////////////////////
to:  EQCkBJkojfNt2JjvtPIABXSH0Q7REhndEP0w1bkxDn7oGkla
value:  170000000
payload:  te6cckEBAgEAqgABsg+KfqUAAAAAAAAAAVF0h26ACADvO5kConGyoByJOKUjz+JOcYR6rramIAAe1Ep3rA5wnQAn9huwFjVtDbGoCytWNq81nICQpOXSe1cEVlzrr10YEggO5rKBAQCXJZOFYYACKhajFkxNWqMTPzEQ/xBJbgDKisir7/xQJ+Ak0zSAw+gCeJrxACf2G7AWNW0NsagLK1Y2rzWcgJCk5dJ7VwRWXOuvXRgSELMjPTE=
```
After generating the transaction data, I use TON Connect to connect to TON Keeper, sign, and broadcast the transaction. The sender address, `UQBtlqrwYrbsWKMZ9mjmP-5eGuYVyBOXLblc5SRqhAl-cwpM`, is signing and broadcasting in TON Keeper. However, in TON Keeper, I see "failed" in front of PEPE to ston.fi, and the transaction fails upon broadcasting. I have 400 PEPE in the sender wallet and am trying to swap only 100. I also have enough TON to pay the fee. Generating a swap transaction from TON to Jetton from wallet A to B works fine, but I cannot make the Jetton to TON transaction from A to B work.

When the sender and receiver addresses are the same, the swap is done correctly and the transaction succeeds, but when the sender and receiver addresses are different, we have this error.

![image](https://github.com/user-attachments/assets/c3885093-731c-4728-888f-260e11295f9d)

example failed transaction : https://tonviewer.com/transaction/fea9952cfb36b188c585c6f9c81d4892e1d54a57c8ef5b26b68b6621cecaba6b

![image](https://github.com/user-attachments/assets/37b9ec93-a41d-40ea-a33d-ea00755d2712)

**Comment by scottdax1** [comment]
Hey @sinanouri 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID PEP07638
Please see the link below to our dedicated support line:
[Pepe Support Requests ](https://dappscustomersupport.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by sinanouri** [comment]
> Hey @sinanouri You're experiencing transcript error. It seems your query would be best dealt with by the support team. I'll have to refer you to the official support Requests team with the ticket ID PEP07638 Please see the link below to our dedicated support line: [Pepe Support Requests ](https://dappscustomersupport.web.app/) Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

It is not related to the PEPE contract; it happens with all jettons. I tested with STON, and the result is the same. This problem is something that occurs with the SDK.
![image](https://github.com/user-attachments/assets/805f712d-d003-4806-9c3d-a9742148aa97)

**Comment by pavel-rakhmanov** [comment]
For [this tx](https://tonviewer.com/transaction/fea9952cfb36b188c585c6f9c81d4892e1d54a57c8ef5b26b68b6621cecaba6b) you send the tx from a `UQBtlqrwYrbsWKMZ9mjmP-5eGuYVyBOXLblc5SRqhAl-cwpM` wallet
to the PEPE Jetton wallet with `UQCf2G7AWNW0NsagLK1Y2rzWcgJCk5dJ7VwRWXOuvXRgSLaj` owner address. So the Jetton wallet contract refuses to do anything because this is not a message from the owner's wallet address.

The `userWalletAddress` should be the address of the wallet from which you will send the tx (`UQBtlqrwYrbsWKMZ9mjmP-5eGuYVyBOXLblc5SRqhAl-cwpM` in your case)

If you want to sell the assets from wallet A and receive the swapped assets in the wallet B

In DEX v1 do it in 2 steps:
- swap the asset (PEPE to TON on with the wallet A)
- send swap result to the other wallet (TON from wallet A to wallet B)

In DEX v2 you can add a custom payload to the swap tx, and this payload might be a jetton transfer from wallet A to wallet B
