### ISSUE TITLE
account.getLpAccountData() always return "exit_code: 11"

### ISSUE THREAD

**Issue by huoyingyangjie** [ston-fi/sdk#25]
as title

**Comment by huoyingyangjie** [comment]
```
import { TonClient, ContractProvider } from "@ton/ton";
import { DEX } from "@ston-fi/sdk";

const client = new TonClient({
    endpoint: "https://toncenter.com/api/v2/jsonRPC",
});


const account = client.open(new DEX.v1.LpAccount("my account"));
const result = account.getLpAccountData()

console.log(result)
```

**Comment by pavel-rakhmanov** [comment]
Exit code `11`  means no such method exists on a given contract, so the error is probably in the invalid LP account address. Can you provide the real LP account address that caused this error? 

It should work for valid addresses.

```ts
import { TonClient } from "@ton/ton";
import { DEX } from "@ston-fi/sdk";

const client = new TonClient({
  endpoint: "https://toncenter.com/api/v2/jsonRPC",
});

const router = client.open(new DEX.v1.Router());

const pool = client.open(
  await router.getPool({
    token0: "EQA2kCVNwVsil2EM2mB0SkXytxCqQjS4mttjDpnXmwG9T6bO", // STON
    token1: "EQBX6K9aXVl3nXINCyPPL86C4ONVmQ8vK360u6dykFKXpHCa", // GEMSTON
  })
);

const lpAccount = client.open(
  await pool.getLpAccount({
    ownerAddress: "EQAQnxLqlX2B6w4jQzzzPWA8eyWZVZBz6Y0D_8noARLOaB3i" // Test wallet
  })
);

const lpAccountData = await lpAccount.getLpAccountData();

console.log(lpAccountData);
```

**Comment by huoyingyangjie** [comment]
Code you provided can't run on my machine. This is my addresss "UQBJVc3J_79EPvrnZ9lSki11RhzSXV1atdyzKhbkcIvmzAXy". An other, I call '/runGetMethod'  for 'get_lp_account_data'  from  "https://toncenter.com/api/v2/" , it also returns "exit_code: 11".

**Comment by pavel-rakhmanov** [comment]
The address you provide (`UQBJVc3J_79EPvrnZ9lSki11RhzSXV1atdyzKhbkcIvmzAXy`) looks like it is your **wallet address**, not an **LP account address**. Is it an address you pass as a value for the LpAccount instance? 

If so, then calling `get_lp_account_data` on this address will cause a fair error because the `wallet_v4r2` contract does not have such a method.  If not, and you used a different address for the LpAccount instance and still got the error, please provide this address for reproducing purposes. 

---

By looking at the state of a [UQBJVc3J_79EPvrnZ9lSki11RhzSXV1atdyzKhbkcIvmzAXy](https://tonviewer.com/EQBJVc3J_79EPvrnZ9lSki11RhzSXV1atdyzKhbkcIvmzFg3) wallet I will assume you are trying to get a LP account state for a USD₮-pTON pool. 

If my assumption is correct, the LP account address you are looking for is [EQAmf9zcZGS59rA-8HXl4ehJoh3nKK-kq_l3YxFyQjBHvHQr](https://tonviewer.com/EQAmf9zcZGS59rA-8HXl4ehJoh3nKK-kq_l3YxFyQjBHvHQr). I get it by running following code:

```ts
const pool = client.open(
  new DEX.v1.Pool('EQD8TJ8xEWB1SpnRE4d89YO3jl0W0EiBnNS4IBaHaUmdfizE') // USD₮-pTON pool
)

const lpAccount = client.open(
  await pool.getLpAccount({
    ownerAddress: "UQBJVc3J_79EPvrnZ9lSki11RhzSXV1atdyzKhbkcIvmzAXy" // owner address
  })
);

console.log(lpAccount.address);
```

And you can get the state of the LP account by running `get_lp_account_data` method with the TON API or with the following code:

```ts
const lpAccountData = await lpAccount.getLpAccountData();

console.log('lpAccountData', lpAccountData);
```

**Comment by huoyingyangjie** [comment]
Thank you so much. I got it.
