### ISSUE TITLE
Swap ton to jetton not working

### ISSUE THREAD

**Issue by Haianh9999** [ston-fi/sdk#35]
@pavel-rakhmanov 
Hello, when i swap ton to jetton i get transaction fail
Please check this transaction: https://tonviewer.com/transaction/ce62eb5e7a50070a55294d57dfbccb55489d28771cb16fc1525c510d85829273

**Comment by pavel-rakhmanov** [comment]
I can assure you that the swap is working as expected.

Your [TX](https://tonviewer.com/transaction/f037df7226f3a33cc8f65de2375a0159f4f6e5e0ecc772a44e5cdf8cdd55af33) failed because you tried to sell 0.001 TON for 0.1 STON while the 0.1 STON current price is ~0.07 TON. The swap could not be performed in this configuration, and transaction bounce from the router([see the message from the router contract](https://tonviewer.com/transaction/d12f41bd492c69a616a428b40fe4e0b6a27ae8dcb2b3979a5f81796467d2b904))

![Screenshot 2024-10-03 at 14 38 08](https://github.com/user-attachments/assets/e25cb5cb-a9f5-4b2e-af23-6349f27d14b8)
